### ISSUE TITLE
What's the difference between PN7150 and PN548

### ISSUE THREAD

**Issue by ef08061108** [NXPNFCLinux/nxpnfc_android_q#1]
What's the difference between pn7150 and pn548？

**Comment by jgeslin** [comment]
PN548 and PN7150 are both NXP's NCI 1.1 based NFC Controllers. PN548 targets mobile and wearable application while PN7150 is a mass market product fulfilling any other application. There are based on same HW but have different internal firmware (fitting with expected application).
