### ISSUE TITLE
HAL getting stuck (read - waiting for irq forever)

### ISSUE THREAD

**Issue by gibsson** [NXPNFCLinux/nxpnfc_android_q#6]
Hi,

I've integrated the NFC driver + HAL into an i.MX 8M Mini Android 10 build (using a PN7150).

Everything looks ok, the initialization goes on, lots of transfers happening happily until the HAL requests a read that never happens as the IRQ that authorizes the read never happens.

I've tried changing the driver wait_event_interruptible() to wait_event_interruptible_timeout() but the HAL doesn't really like having ETIMEDOUT returned.

Here are both dmesg and logcat logs:
https://gist.github.com/gibsson/08b76b6a13dab9a008e971534a3509ac

It always happens at the exact same spot, after exactly 26 interrupts:
```
# cat /proc/interrupts | grep pn                                                                                                                                            
 68:         26          0          0          0  gpio-mxc   8 Level     pn547
```

Note that I've modified the kernel driver to print the buffers sent/received for debugging purposes but the behavior is the same without those traces.
Let me know if you have any hints.

Thanks,
Gary

**Comment by jgeslin** [comment]
Hi,

From both traces (dmesg and logcat) the behavior looks as expected. The NFC initialization completed, ending by the start of the discovery loop. No more exchange with the NFC controller is expected until a remote NFC device or card is being brought close to the PN7150 antenna. This would then trigger IRQ going high to signal the detection of this remote device.

Regards,
Jeremy.

**Comment by gibsson** [comment]
Hi Jeremy,

Thanks for the quick reply. Indeed it seems normal to be in that state, I saw this line afterwards:
https://android.googlesource.com/platform/hardware/nxp/nfc/+/refs/heads/android10-dev/halimpl/hal/phNxpNciHal.cc#376

Clearly in my case when I approach a TAG (I even tried different types) nothing happens.
So my guess is that something is wrong with the HW but I'm not sure how to test it further at this point.

Just to be sure, do you confirm that your libnfc-nxp.conf should work on any design that uses a crystal?
https://github.com/NXPNFCLinux/nxpnfc_android_q/blob/master/hw/pn7150/libnfc-nxp.conf

BTW I think you need to update NfcFactoryTest as its ioctl declaration doesn't work on 64-bit platforms:
https://github.com/NXPNFCLinux/nxpnfc_android_q/blob/master/FactoryTestApp/NfcFactoryTestApp.c#L30
(should be unsigned int instead of unsigned long to match the kernel driver)

Regards,
Gary

**Comment by jgeslin** [comment]
Hi,

If nothing happens when a tag is approached it could be several reasons:
- clock: 
o is your crystal is not 27MHz ?
o is the configuration reflecting this (NXP_SYS_CLK_SRC_SEL=0x01 in libnfc-nxp.conf) ?
- supply:
o is VBAT1 properly supplied above 2.7V ?

Regarding the NfcFactoryTest, you're fully right. Thanks for the hint.

Regards,
Jeremy

**Comment by gibsson** [comment]
Hi,

Yes the crystal is a 27.12MHz (ECS-271.2-10-47Q-ES-TR). So yes the NXP_SYS_CLK_SRC_SEL is 1 as I use the libnfc-nxp.conf as-is.

Supply, yes all our VBATx signals are tied to 3.3V. Does NXP_EXT_TVDD_CFG need to be changed if we aren't using 5V?

For the FactoryTest, I can actually submit a PR if you want as I had to fix it locally.

Regards,
Gary

**Comment by gibsson** [comment]
Hi,

After checking the HW it appeared it was an issue with the BOM and he capacitance that were mounted. It is working now.

Thanks for your support, much appreciated!

Regards,
Gary
